version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: projeto_mysql
    restart: always
    environment:
      MYSQL_DATABASE: projeto
      MYSQL_USER: teste         
      MYSQL_PASSWORD: testesenha123
      MYSQL_ROOT_PASSWORD: roottestesenha123
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql                 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: projeto_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: roottestesenha123
  apache: 
    build: .
    container_name: projeto_apache
    ports:
      - "8000:80"
    volumes:
      - /home/samuel/Documents/ProjetoFacul:/var/www/html
      - /home/samuel/Documents/ProjetoFacul/APACHE/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
volumes:
  mysql_data: 